# Fonte
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Janela e Espaçamento
window_padding_width 12
background_opacity 1.0
confirm_os_window_close 0

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Atalhos de Clipboard
# Ctrl+C: copia se tiver seleção, senão manda SIGINT normalmente
map ctrl+c copy_or_interrupt
# Ctrl+V: cola sempre (sem conflitos)
map ctrl+v paste_from_clipboard

copy_on_select no
enable_audio_bell no

# Shell padrão no Kitty
shell /usr/bin/fish

# Tema Escuro Profundo (AMOLED Dark)
include themes/amoled-black.conf


# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME