"$schema" = 'https://starship.rs/config-schema.json'

# Prompt limpo, escuro e moderno
format = """
$username\
$directory\
$git_branch\
$git_status\
$python\
$character"""

right_format = """
$cmd_duration\
$time"""

add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[username]
show_always = false
style_user = "bold blue"
format = "[$user]($style) "

[directory]
style = "bold cyan"
truncation_length = 4
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'

[python]
symbol = "🐍 "
style = "bold yellow"
format = '[(\($virtualenv\) )]($style)'

[cmd_duration]
min_time = 2_000
style = "dimmed yellow"
format = "took [$duration]($style) "

[time]
disabled = false
time_format = "%R"
style = "dimmed white"
format = "[$time]($style)"
